services:
  - type: web
    name: mutsumi-saki-api
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./prisma/prod.db
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/prisma
      sizeGB: 1
